### ISSUE TITLE
sqlite3 not detected

### ISSUE THREAD

**Issue by prismplex** [InvoiceShelf/InvoiceShelf#228]
### Issue filing pre-requisites

- [X] I've checked the documentation.
- [X] I've looked for similar issues both Open and Closed.
- [X] Ive tried clearing both cache and cookies in my browser or tried opening the app in the Incognito/InPrivate window.

### Describe the bug

Trying to update from 1.3.0 to 2.0.0. Update is not allowed since the requirements are not met (sqlite3 missing). phpinfo shows pdo_sqlite and sqlite3. Also tried reinstalling completely, sqlite3 not detected as installed.

### Steps to Reproduce the issue

Trying to update from 1.3.0 to 2.0.0. Update is not allowed since the requirements are not met (sqlite3 missing). phpinfo shows pdo_sqlite and sqlite3. Also tried reinstalling completely, sqlite3 not detected as installed.

### Expected behavior

Should detect installed sqlite3.

### Actual behavior

Cannot update since installed sqlite3 modulte is not detected.

### InvoiceShelf version

v1.3.0

### PHP version

v8.3.11

### Database type

MariaDB

### Database version

v11.5.2

### Web Browser

LibreWolf/Chromium

### Server OS

Manjaro (Arch Linux)

### Reverse-proxy logs

```irc logs
empty log
```

### Laravel/PHP logs

```irc logs
#37 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#39 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#40 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#42 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#44 /home/thomson/nginx/crater/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(61): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(165): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middlewar>
#46 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/thomson/nginx/crater/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(24): Illuminate\\Pipeline\\Pipeline->then()
#48 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#49 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#51 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#52 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#53 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#54 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#55 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#56 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#58 /home/thomson/nginx/crater/app/Http/Middleware/ConfigMiddleware.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): InvoiceShelf\\Http\\Middleware\\ConfigMiddleware->handle()
#60 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#62 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#64 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#65 /home/thomson/nginx/crater/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
```

**Comment by rihards-simanovics** [comment]
@prismplex what php-fpm handler are you using in the reverse proxy config? Perhaps your handler is different from your OS's PHP-CLI?

**Comment by rihards-simanovics** [comment]
> Well, shame on me. You are right, I specified the wrong handler, the old php 8.2. After changing, the upgrade went flawlessly. Sometimes when you are stuck at a point you need somebody taking a step backwards to find the problem. Thank you! My fault no issue, can be closed.

Hey @prismplex, no worries, happens to the best of us. Glad this solved your issue.
